import 'package:flutter/material.dart';
import 'package:supercharged/supercharged.dart';

final Color dasarDark = '343540'.toColor();
final Color navigasiDark = '202123'.toColor();
final Color chatUserDark = '40424D'.toColor();
final Color textDark = 'FFFFFF'.toColor();
final Color textFieldDark = '40414E'.toColor();
final Color buttonDark = 'A5A5A5'.toColor();
final Color warnaUtama = 'FF6969'.toColor();

final Color dasarLight = 'F2F2F2'.toColor();
final Color navigasiLight = 'D1D1D1'.toColor();
final Color chatUserLight = 'FFF4F4'.toColor();
final Color textLight1 = '5E5E5E'.toColor();
final Color textLight2 = '959595'.toColor();
final Color textLight3 = '484848'.toColor();
final Color textLight4 = '959595'.toColor();
final Color textLight5 = Colors.black;
final Color textLight6 = 'C0C0C0'.toColor();
final Color textLight7 = '424242'.toColor();
final Color textLight8 = '555555'.toColor();
final Color textLight9 = '323232'.toColor();
final Color textLight10 = '989797'.toColor();
final Color textLight11 = '6D6D6D'.toColor();
final Color shadow = Colors.grey;
final Color textFieldLight = 'F2F2F2'.toColor();
final Color buttonLight1 = '737373'.toColor();
final Color buttonLight2 = 'FFE0E0'.toColor();
final Color contohLight = 'FFF4F4'.toColor();
final Color frekuensiLight = '444444'.toColor();
final Color divider = 'ECECEC'.toColor();
final Color border = 'B8B8B8'.toColor();
